version: "3.8"
services:
  db: 
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_llm
    
    ports: ["5432:5432"]

  qdrant: 
    image: qdrant/qdrant:v1.3
    ports: ["6333:6333"]

  
  app: 
    build: .
    depends_on:
    - db
    - qdrant

    env_files:
      - .env 
    ports: 
      - "3000:3000"

      